// import { CardType } from "./cards.dto"

// const defaultCard: CardType = {
//    _id: 0,
//    title: "New Card",
//    level: 1,
//    price: 1,
//    rph: 10,
//    salary: 100,
//    progress: 1,
//    description: "Купи меня",
//    urlPicture: "https://via.placeholder.com/150",
//    dateCreation: "2024-09-09",
//    upgradeCost: 1000,
//  }


// export const cards: CardType[] = [
//    {
//     ...defaultCard,
//      _id: 1,
//      title: "ХаудиХо",
//      level: 3,
//      price: 199,
//      rph: 10,
//      description: "Купи меня",
//      urlPicture: "https://via.placeholder.com/150",
//     //  variant: "default",
//    },
//    {
//     ...defaultCard,
//      _id: 2,
//      title: "Marmok",
//      level: 5,
//      price: 100,
//      rph: 30,
//      description: "Описание карточки 2",
//      urlPicture: "https://via.placeholder.com/150",
//     //  variant: "new",
//    },
//    {
//     ...defaultCard,
//       _id: 3,
//      title: "EeOneGuy",
//      level: 1,
//      price: 39,
//      rph: 20,
//      description: "Описание карточки 3",
//      urlPicture: "https://via.placeholder.com/150",
//     //  variant: "approved",
//    },
//    {
//      ...defaultCard,
//      _id: 4,
//      level: 3,
//      price: 19,
//      rph: 10,
//      description: "Описание карточки 4",
//      urlPicture: "https://via.placeholder.com/150",
//     //  variant: "default",
//    },
//    {
//      ...defaultCard,
//      _id: 5,
//      level: 3,
//      price: 19,
//      rph: 15,
//      description: "Описание карточки 5",
//      urlPicture: "https://via.placeholder.com/150",
//     //  variant: "new",
//    },
//    {
//      ...defaultCard,
//      _id: 6,
//      level: 3,
//      price: 19,
//      rph: 30,
//      description: "Описание карточки 6",
//      urlPicture: "https://via.placeholder.com/150",
//     //  variant: "new",
//    },
//    {
//      ...defaultCard,
//      _id: 7,
//    },
//  ]